import Image from 'next/image'
import Link from 'next/link'
import { desc, eq } from 'drizzle-orm'
import { db } from '@/lib/db/client'
import { products as productsTable } from '@/lib/db/schema'

async function getFeaturedProducts() {
  try {
    return await db.query.products.findMany({ where: eq(productsTable.status, 'published'), orderBy: [desc(productsTable.featured), desc(productsTable.createdAt)], with: { productImages: true }, limit: 4 })
  } catch {
    return []
  }
}

const fallbackProducts = [
  { name: 'Luna Curved Sofa', manufacturer: 'Visionnaire', image: '/prototype/cat-vis-sofa.jpg' },
  { name: 'Fiore Dining Armchair', manufacturer: 'Dolce & Gabbana Casa', image: '/prototype/cat-dg-dining.jpg' },
  { name: 'Helleno Vanity Console', manufacturer: 'Versace Home', image: '/prototype/cat-versace-vanity.jpg' },
]

export async function PrototypeHomepage() {
  const products = await getFeaturedProducts()
  const featured = products.slice(0, 3).map((product, index) => ({ name: product.name, manufacturer: product.brand || 'The Revamp UG', image: product.productImages?.find((entry) => entry.isPrimary)?.url || product.productImages?.[0]?.url || fallbackProducts[index]?.image || '/prototype/cat-sofa.jpg' }))
  const cards = featured.length === 3 ? featured : fallbackProducts
  return (
    <>
      <section className="px-6 pb-24 pt-16 lg:px-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col items-end gap-16 lg:flex-row"><div className="w-full lg:w-3/5"><div className="mb-8 inline-flex items-center gap-3"><span className="h-px w-8 bg-gilded" /><span className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">Sourcing Excellence</span></div><h1 className="mb-8 whitespace-pre-line font-serif text-5xl font-medium leading-[1.05] text-balance md:text-6xl lg:text-8xl">The architecture{`\n`}of refined living.</h1><p className="mb-12 max-w-[48ch] text-lg leading-relaxed text-muted-foreground md:text-xl">Uganda&apos;s premier gateway to European master-craftsmanship and bespoke architecture. We source, design, import and install the extraordinary.</p><div className="flex items-center gap-8"><Link href="/collections" className="group flex items-center gap-3 border-b border-border pb-1 text-sm font-medium hover:border-gilded">Explore the Catalog <span className="transition-transform group-hover:translate-x-1">→</span></Link><Link href="/services" className="text-sm font-medium text-muted-foreground hover:text-foreground">Our services →</Link></div></div><div className="w-full lg:w-2/5"><div className="relative"><Image src="/prototype/hero-villa.jpg" alt="A minimalist luxury villa interior in Kampala with warm light and stone walls" width={1080} height={1344} className="aspect-[3/4] w-full rounded-md object-cover" /><div className="absolute -bottom-6 -left-6 hidden max-w-xs rounded-sm bg-obsidian p-8 text-canvas ring-1 ring-white/10 md:block"><p className="font-serif text-2xl italic leading-tight">&quot;A new standard for East African luxury.&quot;</p><p className="mt-4 text-[10px] uppercase tracking-widest opacity-50">Private Client, Kololo</p></div></div></div></div></div></section>
      <section className="border-y border-border bg-white/40 py-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-12 overflow-hidden px-6 opacity-50 transition-opacity duration-700 hover:opacity-80"><span className="whitespace-nowrap font-serif text-sm uppercase tracking-[0.3em] lg:text-lg">Dolce &amp; Gabbana</span><span className="whitespace-nowrap font-serif text-sm uppercase tracking-[0.3em] lg:text-lg">Boca do Lobo</span><span className="whitespace-nowrap font-serif text-sm uppercase tracking-[0.3em] lg:text-lg">Fendi Casa</span><span className="hidden whitespace-nowrap font-serif text-sm uppercase tracking-[0.3em] sm:inline lg:text-lg">Versace Home</span><span className="hidden whitespace-nowrap font-serif text-sm uppercase tracking-[0.3em] lg:inline lg:text-lg">Visionnaire</span></div></section>
      <section className="px-6 py-24 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col gap-16 lg:flex-row"><aside className="w-full shrink-0 lg:w-48"><h3 className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">This Season</h3><p className="mt-6 font-serif text-2xl leading-snug">A handful of pieces newly arrived in our private holding.</p><Link href="/collections" className="mt-6 inline-block border-b border-foreground pb-0.5 text-[11px] font-medium uppercase tracking-[0.2em]">See full catalog</Link></aside><div className="flex-1"><div className="grid grid-cols-1 gap-x-12 gap-y-20 sm:grid-cols-2"><Link href="/collections" className="group sm:col-span-2"><div className="relative mb-8 overflow-hidden rounded-md"><Image src="/prototype/feature-console.jpg" alt="Boca do Lobo Newton Console Gold" width={1600} height={896} className="aspect-[16/9] w-full object-cover transition-transform duration-1000 group-hover:scale-[1.02] lg:aspect-[21/9]" /><div className="absolute bottom-8 left-8"><span className="bg-canvas px-4 py-2 text-[10px] font-bold uppercase tracking-widest ring-1 ring-border">Limited Edition</span></div></div><div className="flex items-end justify-between"><div><p className="mb-2 text-[10px] uppercase tracking-[0.2em] text-gilded">Boca do Lobo</p><h4 className="font-serif text-3xl font-medium">Newton Console Gold</h4></div><span className="hidden text-sm text-muted-foreground sm:block">Bespoke commission only</span></div></Link>{cards.map((item) => <Link href="/collections" key={item.name} className="group"><div className="relative mb-6 overflow-hidden rounded-md"><Image src={item.image} alt={item.name} width={800} height={1000} className="aspect-[4/5] w-full object-cover transition-transform duration-700 group-hover:scale-[1.03]" /></div><p className="mb-2 text-[10px] uppercase tracking-[0.2em] text-gilded">{item.manufacturer}</p><h4 className="font-serif text-2xl font-medium">{item.name}</h4></Link>)}</div></div></div></section>
      <section className="bg-obsidian px-6 py-32 text-canvas lg:px-12"><div className="mx-auto grid max-w-7xl items-center gap-24 lg:grid-cols-2"><div className="space-y-12"><h2 className="whitespace-pre-line font-serif text-4xl leading-[1.1] text-balance md:text-5xl">We do not just import furniture; we curate legacies.</h2><div className="space-y-10">{[['01','The Global Search','Bypassing standard retail to secure premium architectural pieces from exclusive global design houses.'],['02','White-Glove Logistics','Custom-crated freight, customs handling and temperature-controlled transit to Kampala.'],['03','Atelier Installation','Trained installers position, level and style each piece for the architecture it lives in.']].map(([number,title,body]) => <div key={number} className="group flex gap-6"><div className="flex size-10 shrink-0 items-center justify-center rounded-full border border-gilded/30 text-sm text-gilded transition-colors group-hover:bg-gilded group-hover:text-obsidian">{number}</div><div className="space-y-2"><h5 className="text-lg font-medium tracking-wide">{title}</h5><p className="max-w-[40ch] text-base leading-relaxed text-canvas/55">{body}</p></div></div>)}</div><Link href="/services" className="inline-flex items-center gap-3 border-b border-canvas/30 pb-1 text-[11px] font-medium uppercase tracking-[0.2em] hover:border-gilded">The full service ethos <span>→</span></Link></div><div className="grid grid-cols-2 gap-4"><Image src="/prototype/process-1.jpg" alt="Gilded craftsmanship detail" width={600} height={800} className="aspect-[3/4] w-full rounded-sm object-cover" /><Image src="/prototype/process-2.jpg" alt="Interior styling moodboard" width={600} height={800} className="mt-12 aspect-[3/4] w-full rounded-sm object-cover" /></div></div></section>
    </>
  )
}
