import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight } from '@/components/ui/luxury-icons'
import { getPublishedSearchData } from '@/lib/db/queries'

const fallbackProducts = [
  { name: 'Audo Lounge Chair', image: '/prototype/cat-minotti-chair.jpg', slug: '' },
  { name: 'Travertine Dining Table', image: '/prototype/cat-table.jpg', slug: '' },
  { name: 'FLOS Table Lamp', image: '/prototype/cat-vis-lamp.jpg', slug: '' },
  { name: 'Tuxedo Accent Chair', image: '/prototype/cat-versace-chair.jpg', slug: '' },
]

function imageFrom(...values: unknown[]) { for (const value of values) { if (typeof value === 'string' && value.trim()) return value; if (Array.isArray(value) && typeof value[0] === 'string') return value[0] } return '/prototype/hero-natural-light.jpg' }

export async function PrototypeHomepage() {
  const searchData = await getPublishedSearchData().catch(() => ({ products: [], projects: [], articles: [], services: [] }))
  const products = searchData.products.slice(0, 4).map((product, index) => ({ name: product.name, image: imageFrom(product.ogImage, product.productImages?.find((entry) => entry.isPrimary)?.url, product.productImages?.[0]?.url, fallbackProducts[index].image), slug: product.slug }))
  const cards = products.length ? products : fallbackProducts
  const services = searchData.services.slice(0, 4)
  const projects = searchData.projects.slice(0, 2)
  const articles = searchData.articles.slice(0, 3)
  const featured = projects[0]

  return <>
    <section className="relative min-h-[calc(100svh-5rem)] overflow-hidden bg-obsidian text-ivory"><Image src="/prototype/hero-villa.jpg" alt="The architecture of refined living" fill priority className="object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/35 to-black/10" /><div className="relative mx-auto flex min-h-[calc(100svh-5rem)] max-w-[1440px] items-end px-5 pb-12 pt-28 sm:px-8 sm:pb-16 lg:px-12"><div className="max-w-3xl"><p className="text-[10px] uppercase tracking-[0.3em] text-ivory/65">The Revamp UG</p><h1 className="mt-6 max-w-2xl font-serif text-6xl font-light leading-[0.84] sm:text-8xl lg:text-[7rem]">The Architecture<br />of Refined Living.</h1><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-[9px] uppercase tracking-[0.2em] text-ivory/60"><span>Interiors</span><span>Architecture</span><span>Global sourcing</span></div><Link href="/collections" className="mt-10 inline-flex min-h-11 items-center gap-3 border-b border-ivory/45 pb-2 text-[10px] uppercase tracking-[0.18em]">Explore our world <ArrowRight className="size-4" /></Link></div></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[0.8fr_1fr_0.65fr] lg:gap-16"><div><p className="text-[10px] uppercase tracking-[0.28em] text-muted-foreground">About Revamp</p><h2 className="mt-5 font-serif text-5xl leading-[0.9] sm:text-6xl">More than spaces.<br />A more meaningful way of living.</h2></div><div className="text-sm leading-7 text-muted-foreground"><p>We create considered spaces, source exceptional pieces, and help complete environments feel at home. Our work brings architecture, interiors, and objects together with clarity.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-foreground underline underline-offset-4">Our story <ArrowRight className="size-3" /></Link></div><div className="relative min-h-64 overflow-hidden"><Image src="/prototype/feature-console.jpg" alt="Spaces that feel like you" fill className="object-cover" /></div></div></section>

    {services.length > 0 && <section className="border-y border-border bg-muted/20 px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="flex items-end justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[0.28em] text-muted-foreground">Our services</p><h2 className="mt-4 font-serif text-5xl leading-[0.9] sm:text-6xl">A complete design experience.</h2></div><Link href="/services" className="hidden text-[10px] uppercase tracking-[0.18em] sm:block">View all <ArrowRight className="ml-1 inline size-3" /></Link></div><div className="mt-10 grid grid-cols-2 gap-2 md:grid-cols-4">{services.map((service, index) => <Link key={service.id} href={`/services/${service.category?.slug || 'services'}/${service.slug}`} className="group"><div className="relative aspect-[4/5] overflow-hidden bg-muted"><Image src={imageFrom(service.image, fallbackProducts[index].image)} alt={service.name} fill className="object-cover transition duration-500 group-hover:scale-105" /></div><p className="mt-3 text-[9px] uppercase tracking-[0.14em] text-muted-foreground">{service.category?.name || 'Service'}</p><h3 className="mt-1 font-serif text-xl leading-none">{service.name}</h3></Link>)}</div></div></section>}

    {featured && <section className="relative overflow-hidden bg-obsidian text-ivory"><Image src={imageFrom(featured.thumbnailImage, featured.ogImage, featured.images, featured.gallery, '/prototype/hero-villa.jpg')} alt={featured.title} fill className="object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" /><div className="relative mx-auto flex min-h-[28rem] max-w-[1440px] items-end px-5 pb-10 sm:px-8 sm:pb-14 lg:px-12"><div><p className="text-[10px] uppercase tracking-[0.28em] text-ivory/60">Featured project</p><h2 className="mt-3 font-serif text-5xl leading-none sm:text-6xl">{featured.title}</h2><p className="mt-3 text-xs uppercase tracking-[0.16em] text-ivory/65">{featured.location || 'Kampala, Uganda'}</p><Link href={`/portfolio/${featured.slug}`} className="mt-7 inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] underline underline-offset-4">View project <ArrowRight className="size-3" /></Link></div></div></section>}

    <section className="px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[0.28em] text-muted-foreground">The collection</p><h2 className="mt-4 font-serif text-5xl leading-[0.9] sm:text-6xl">Objects for Refined Living.</h2></div><Link href="/collections" className="text-[10px] uppercase tracking-[0.18em]">View all <ArrowRight className="ml-1 inline size-3" /></Link></div><div className="mt-10 grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-4">{cards.map((item, index) => <Link key={`${item.name}-${index}`} href={item.slug ? `/collections/${item.slug}` : '/collections'} className="group"><div className="relative aspect-[4/5] overflow-hidden bg-muted"><Image src={item.image} alt={item.name} fill className="object-cover transition duration-500 group-hover:scale-105" /></div><p className="mt-3 text-[9px] uppercase tracking-[0.14em] text-muted-foreground">The Revamp collection</p><h3 className="mt-1 font-serif text-xl leading-none">{item.name}</h3></Link>)}</div></div></section>

    <section className="grid bg-obsidian text-ivory sm:grid-cols-2"><div className="flex min-h-80 flex-col justify-center px-5 py-12 sm:px-8 lg:px-12"><p className="text-[10px] uppercase tracking-[0.28em] text-ivory/60">Source the exceptional.</p><h2 className="mt-5 max-w-md font-serif text-5xl leading-[0.9]">From the world&apos;s best brands to independent makers.</h2><p className="mt-5 max-w-md text-sm leading-6 text-ivory/65">We find, procure, and deliver extraordinary pieces anywhere in the world.</p><Link href="/source-with-revamp" className="mt-8 inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] underline underline-offset-4">Discover sourcing <ArrowRight className="size-3" /></Link></div><div className="relative min-h-80"><Image src="/prototype/process-2.jpg" alt="Material sourcing detail" fill className="object-cover opacity-80" /></div></section>

    {articles.length > 0 && <section className="px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[0.28em] text-muted-foreground">The Revamp edit</p><h2 className="mt-4 font-serif text-5xl leading-[0.9] sm:text-6xl">Ideas. Insights. Inspiration.</h2></div><Link href="/journal" className="text-[10px] uppercase tracking-[0.18em]">Read all <ArrowRight className="ml-1 inline size-3" /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{articles.map((article) => <Link key={article.id} href={`/journal/${article.slug}`} className="group"><div className="relative aspect-[4/3] overflow-hidden bg-muted"><Image src={imageFrom(article.featuredImage, '/prototype/process-1.jpg')} alt={article.title} fill className="object-cover transition duration-500 group-hover:scale-105" /></div><p className="mt-3 text-[9px] uppercase tracking-[0.14em] text-muted-foreground">{article.category || 'Journal'}</p><h3 className="mt-1 font-serif text-2xl leading-none">{article.title}</h3><span className="mt-3 block text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Read more <ArrowUpRight className="ml-1 inline size-3" /></span></Link>)}</div></div></section>}

    <section className="bg-muted/30 px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto flex max-w-[1100px] flex-col items-start justify-between gap-8 border-y border-border py-10 sm:flex-row sm:items-end"><div><p className="text-[10px] uppercase tracking-[0.28em] text-muted-foreground">Let&apos;s create what&apos;s next.</p><h2 className="mt-4 font-serif text-5xl leading-[0.9] sm:text-6xl">A calmer, more beautiful world.</h2></div><Link href="/book-consultation" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-obsidian px-5 text-[10px] uppercase tracking-[0.16em] text-ivory">Start a conversation <ArrowRight className="size-3" /></Link></div></section>
  </>
}
