import Image from 'next/image'
import Link from 'next/link'
import { getPublishedSearchData } from '@/lib/db/queries'

const fallbackProducts = [
  { name: 'Luna Curved Sofa', manufacturer: 'Visionnaire', image: '/prototype/cat-vis-sofa.jpg', slug: '' },
  { name: 'Fiore Dining Armchair', manufacturer: 'Dolce & Gabbana Casa', image: '/prototype/cat-dg-dining.jpg', slug: '' },
  { name: 'Helleno Vanity Console', manufacturer: 'Versace Home', image: '/prototype/cat-versace-vanity.jpg', slug: '' },
]

function imageFrom(...values: unknown[]) {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value
    if (Array.isArray(value) && typeof value[0] === 'string') return value[0]
  }
  return '/prototype/process-1.jpg'
}

export async function PrototypeHomepage() {
  const searchData = await getPublishedSearchData().catch(() => ({ products: [], projects: [], articles: [], services: [] }))
  const products = searchData.products.slice(0, 4).map((product, index) => ({ name: product.name, manufacturer: 'The Revamp collection', image: imageFrom(product.ogImage, product.productImages?.find((entry) => entry.isPrimary)?.url, product.productImages?.[0]?.url, fallbackProducts[index % fallbackProducts.length].image), slug: product.slug }))
  const cards = products.length ? products : fallbackProducts
  const services = searchData.services.slice(0, 3)
  const articles = searchData.articles.slice(0, 3)
  const projects = searchData.projects.slice(0, 3)
  return <>
    <section className="px-6 pb-24 pt-16 lg:px-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col items-end gap-16 lg:flex-row"><div className="w-full lg:w-3/5"><div className="mb-8 inline-flex items-center gap-3"><span className="h-px w-8 bg-gilded" /><span className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">Sourcing Excellence</span></div><h1 className="mb-8 whitespace-pre-line font-serif text-5xl font-medium leading-[1.05] text-balance md:text-6xl lg:text-8xl">The architecture{`\n`}of refined living.</h1><p className="mb-12 max-w-[48ch] text-lg leading-relaxed text-muted-foreground md:text-xl">Uganda&apos;s premier gateway to European master-craftsmanship and bespoke architecture. We source, design, import and install the extraordinary.</p><div className="flex flex-wrap items-center gap-8"><Link href="/collections" className="group flex items-center gap-3 border-b border-border pb-1 text-sm font-medium hover:border-gilded">Explore the collection <span className="transition-transform group-hover:translate-x-1">→</span></Link><Link href="/book-consultation" className="text-sm font-medium text-muted-foreground hover:text-foreground">Begin a private consultation →</Link></div></div><div className="w-full lg:w-2/5"><div className="relative"><Image src="/prototype/hero-villa.jpg" alt="A minimalist luxury villa interior in Kampala with warm light and stone walls" width={1080} height={1344} className="aspect-[3/4] w-full rounded-md object-cover" /><div className="absolute -bottom-6 -left-6 hidden max-w-xs rounded-sm bg-obsidian p-8 text-canvas ring-1 ring-white/10 md:block"><p className="font-serif text-2xl italic leading-tight">&quot;A new standard for East African luxury.&quot;</p><p className="mt-4 text-[10px] uppercase tracking-widest opacity-50">Private Client, Kololo</p></div></div></div></div></div></section>

    <section className="px-6 py-24 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col gap-16 lg:flex-row"><aside className="w-full shrink-0 lg:w-48"><h3 className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">The current edit</h3><p className="mt-6 font-serif text-2xl leading-snug">A considered selection of pieces newly available through the studio.</p><Link href="/collections" className="mt-6 inline-block border-b border-foreground pb-0.5 text-[11px] font-medium uppercase tracking-[0.2em]">View the collection</Link></aside><div className="flex-1"><div className="grid grid-cols-1 gap-x-12 gap-y-16 sm:grid-cols-2">{cards.map((item, index) => <Link href={item.slug ? `/collections/${item.slug}` : '/collections'} key={`${item.name}-${index}`} className="group"><div className="relative mb-6 overflow-hidden rounded-md"><Image src={item.image} alt={item.name} width={800} height={1000} className="aspect-[4/5] w-full object-cover transition-transform duration-700 group-hover:scale-[1.03]" /></div><p className="mb-2 text-[10px] uppercase tracking-[0.2em] text-gilded">{item.manufacturer}</p><h4 className="font-serif text-2xl font-medium">{item.name}</h4><span className="mt-3 inline-block text-[10px] uppercase tracking-[0.18em] text-muted-foreground group-hover:text-gilded">View piece →</span></Link>)}</div></div></div></section>

    {services.length > 0 && <section className="border-y border-border bg-canvas-dark px-6 py-24 lg:px-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">How we help</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">A studio built around the whole journey.</h2></div><Link href="/services" className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gilded hover:text-obsidian">Explore all services →</Link></div><div className="mt-12 grid gap-px bg-border md:grid-cols-3">{services.map((service, index) => <Link key={service.id} href={`/services/${service.category?.slug || 'services'}/${service.slug}`} className="group bg-canvas-dark p-7 transition-colors hover:bg-canvas"><p className="text-[10px] uppercase tracking-[0.2em] text-gilded">0{index + 1}</p><h3 className="mt-10 font-serif text-3xl leading-tight">{service.name}</h3><p className="mt-4 line-clamp-3 text-sm leading-6 text-muted-foreground">{service.description || 'A considered service shaped around your space, timeline, and point of view.'}</p><span className="mt-7 inline-block text-[10px] uppercase tracking-[0.18em] text-gilded">Discover the service →</span></Link>)}</div></div></section>}

    <section className="bg-obsidian px-6 py-32 text-canvas lg:px-12"><div className="mx-auto grid max-w-7xl items-center gap-24 lg:grid-cols-2"><div className="space-y-12"><h2 className="whitespace-pre-line font-serif text-4xl leading-[1.1] text-balance md:text-5xl">We do not just import furniture; we curate legacies.</h2><div className="space-y-10">{[['01','The Global Search','Bypassing standard retail to secure premium architectural pieces from exclusive global design houses.'],['02','White-Glove Logistics','Custom-crated freight, customs handling and temperature-controlled transit to Kampala.'],['03','Atelier Installation','Trained installers position, level and style each piece for the architecture it lives in.']].map(([number,title,body]) => <div key={number} className="group flex gap-6"><div className="flex size-10 shrink-0 items-center justify-center rounded-full border border-gilded/30 text-sm text-gilded transition-colors group-hover:bg-gilded group-hover:text-obsidian">{number}</div><div className="space-y-2"><h5 className="text-lg font-medium tracking-wide">{title}</h5><p className="max-w-[40ch] text-base leading-relaxed text-canvas/55">{body}</p></div></div>)}</div><Link href="/services" className="inline-flex items-center gap-3 border-b border-canvas/30 pb-1 text-[11px] font-medium uppercase tracking-[0.2em] hover:border-gilded">The full service ethos <span>→</span></Link></div><div className="grid grid-cols-2 gap-4"><Image src="/prototype/process-1.jpg" alt="Gilded craftsmanship detail" width={600} height={800} className="aspect-[3/4] w-full rounded-sm object-cover" /><Image src="/prototype/process-2.jpg" alt="Interior styling moodboard" width={600} height={800} className="mt-12 aspect-[3/4] w-full rounded-sm object-cover" /></div></div></section>

    {projects.length > 0 && <section className="px-6 py-24 lg:px-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">Selected work</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">Spaces with a point of view.</h2></div><Link href="/portfolio" className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gilded">View the portfolio →</Link></div><div className="mt-12 grid gap-6 md:grid-cols-3">{projects.map((project) => <Link key={project.id} href={`/portfolio/${project.slug}`} className="group"><div className="relative aspect-[4/5] overflow-hidden rounded-md bg-muted"><Image src={imageFrom(project.thumbnailImage, project.ogImage, project.images, project.gallery)} alt={project.title} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-700 group-hover:scale-[1.03]" /></div><p className="mt-4 text-[10px] uppercase tracking-[0.2em] text-gilded">{project.category || 'Portfolio'}{project.location ? ` · ${project.location}` : ''}</p><h3 className="mt-2 font-serif text-2xl">{project.title}</h3></Link>)}</div></div></section>}

    {articles.length > 0 && <section className="bg-canvas-dark px-6 py-24 text-canvas lg:px-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">From the journal</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">Notes on considered living.</h2></div><Link href="/journal" className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gilded">Read the journal →</Link></div><div className="mt-12 grid gap-6 md:grid-cols-3">{articles.map((article) => <Link key={article.id} href={`/journal/${article.slug}`} className="group"><div className="relative aspect-[4/3] overflow-hidden rounded-md bg-obsidian"><Image src={imageFrom(article.featuredImage)} alt={article.title} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-700 group-hover:scale-[1.03]" /></div><p className="mt-4 text-[10px] uppercase tracking-[0.2em] text-gilded">{article.category || 'Journal'}</p><h3 className="mt-2 font-serif text-2xl text-canvas">{article.title}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-canvas/60">{article.excerpt || 'A note from the studio.'}</p></Link>)}</div></div></section>}

    <section className="px-6 py-24 lg:px-12"><div className="mx-auto grid max-w-7xl gap-12 border-y border-border py-12 md:grid-cols-[0.8fr_1.2fr] md:items-end md:py-16"><div><p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">A private practice</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">For rooms with a point of view.</h2></div><div className="flex flex-col items-start gap-8 md:items-end"><p className="max-w-xl text-lg leading-relaxed text-muted-foreground md:text-right">From a single heirloom object to a full residence, our work begins with listening carefully to how you want to live.</p><Link href="/contact" className="rounded-full bg-obsidian px-6 py-3 text-[11px] font-semibold uppercase tracking-[0.2em] text-canvas transition-colors hover:bg-gilded hover:text-obsidian">Begin a conversation</Link></div></div></section>
  </>
}
