'use client'

import { FormEvent, useState } from 'react'
import { useClerk, useSession, useSessionList, useUser } from '@clerk/nextjs'
import { Check, Laptop, Loader2, LogOut, Smartphone, Upload } from 'lucide-react'

export function CustomProfileSettings() {
  const { isLoaded, user } = useUser(); const { session: currentSession } = useSession(); const { signOut } = useClerk(); const { sessions } = useSessionList();
  const [firstName, setFirstName] = useState(user?.firstName ?? ''); const [lastName, setLastName] = useState(user?.lastName ?? ''); const [phone, setPhone] = useState(user?.primaryPhoneNumber?.phoneNumber ?? ''); const [address, setAddress] = useState(String(user?.unsafeMetadata?.address ?? '')); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false)
  if (!isLoaded || !user) return <div className="border border-border p-8 text-sm text-muted-foreground">Loading your profile…</div>
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(null); setError(null); try { await user.update({ firstName, lastName, unsafeMetadata: { ...user.unsafeMetadata, phone, address } }); setMessage('Your profile has been updated.') } catch (error) { setError(error instanceof Error ? error.message : 'Unable to update your profile.') } finally { setSaving(false) } }
  const upload = async (file: File) => { setUploading(true); setError(null); try { await user.setProfileImage({ file }); setMessage('Profile picture updated.') } catch (error) { setError(error instanceof Error ? error.message : 'Unable to update your profile picture.') } finally { setUploading(false) } }
  return <div className="grid gap-8"><section className="border border-border bg-card p-6 sm:p-8"><div className="mb-7 flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-primary">Personal details</p><h1 className="mt-2 font-serif text-3xl">Your profile</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Keep the details connected to your Clerk account up to date.</p></div><label className="group relative flex size-20 shrink-0 cursor-pointer items-center justify-center overflow-hidden rounded-full border border-border bg-muted"><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event) => event.target.files?.[0] && upload(event.target.files[0])} />{user.imageUrl ? <img src={user.imageUrl} alt="Profile" className="size-full object-cover" /> : <Upload className="size-5 text-muted-foreground" aria-hidden="true" />}{uploading && <span className="absolute inset-0 flex items-center justify-center bg-background/80"><Loader2 className="size-4 animate-spin" /></span>}</label></div><form onSubmit={save} className="grid gap-5"><div className="grid gap-4 sm:grid-cols-2"><ProfileField label="First name" value={firstName} onChange={setFirstName} /><ProfileField label="Last name" value={lastName} onChange={setLastName} /></div><ProfileField label="Phone number" value={phone} onChange={setPhone} type="tel" /><label className="grid gap-2 text-sm font-medium"><span>Address</span><textarea value={address} onChange={(event) => setAddress(event.target.value)} rows={3} className="border border-border bg-background px-3 py-3 outline-none ring-primary/30 transition focus:ring-2" /></label><p className="text-xs text-muted-foreground">Email: {user.primaryEmailAddress?.emailAddress ?? 'No email on file'}</p>{message && <p className="flex items-center gap-2 text-sm text-primary"><Check className="size-4" />{message}</p>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<button type="submit" disabled={saving} className="flex h-12 w-full items-center justify-center gap-2 bg-primary text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-50 sm:w-fit sm:px-8">{saving && <Loader2 className="size-4 animate-spin" />}{saving ? 'Saving…' : 'Save changes'}</button></form></section><Sessions sessions={sessions ?? []} currentSessionId={currentSession?.id} signOut={signOut} /></div>
}

function ProfileField({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-2 text-sm font-medium"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="h-12 border border-border bg-background px-3 outline-none ring-primary/30 transition focus:ring-2" /></label> }
function Sessions({ sessions, currentSessionId, signOut }: { sessions: any[]; currentSessionId?: string; signOut: (options?: { sessionId?: string }) => Promise<void> }) { return <section id="devices" className="border border-border bg-card p-6 sm:p-8"><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-primary">Account access</p><h2 className="mt-2 font-serif text-2xl">Your devices</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Review active Clerk sessions and sign out devices you no longer recognize.</p><div className="mt-6 grid gap-3">{sessions.map((session) => <div key={session.id} className="flex items-center justify-between gap-4 border-b border-border py-4 last:border-0"><div className="flex min-w-0 items-center gap-3">{session.latestActivity?.deviceType === 'Mobile' ? <Smartphone className="size-5 shrink-0 text-muted-foreground" /> : <Laptop className="size-5 shrink-0 text-muted-foreground" />}<div className="min-w-0"><p className="truncate text-sm font-medium">{session.id === currentSessionId ? 'This device' : (session.latestActivity?.browserName ?? 'Active browser')}</p><p className="text-xs text-muted-foreground">{session.id === currentSessionId ? 'Current session' : (session.latestActivity?.ipAddress ?? 'Signed-in device')}</p></div></div><button type="button" onClick={() => signOut({ sessionId: session.id })} className="shrink-0 text-xs text-muted-foreground underline underline-offset-4 hover:text-destructive">{session.id === currentSessionId ? 'Sign out' : 'Revoke'}</button></div>)}</div><button type="button" onClick={() => signOut()} className="mt-5 flex items-center gap-2 text-sm text-muted-foreground hover:text-destructive"><LogOut className="size-4" />Sign out all devices</button></section> }
