import Image from 'next/image'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'

export const metadata = { title: 'The Studio — The Revamp UG', description: "The Revamp UG is Kampala's specialist in luxury European interior sourcing, architecture, importing and installation. Meet the studio behind East Africa's most refined homes." }

export default function AboutPage() { return <><SiteHeader /><main>
  <section className="px-6 pb-20 pt-16 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-1 items-end gap-12 lg:grid-cols-12"><div className="lg:col-span-7"><div className="mb-6 inline-flex items-center gap-3"><span className="h-px w-8 bg-gilded" /><span className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">The Studio</span></div><h1 className="font-serif text-5xl font-medium leading-[1.05] text-balance md:text-7xl">A quiet practice for <span className="italic">extraordinary</span> interiors.</h1></div><div className="lg:col-span-5"><p className="text-lg leading-relaxed text-muted-foreground">The Revamp UG was founded in Kampala for collectors who refused to compromise on quality, provenance or service. We bridge a private network of European maisons with East Africa&apos;s most ambitious residences — and design spaces of our own.</p></div></div></section>
  <section className="px-6 pb-24 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-2 md:grid-cols-3"><Image src="/prototype/hero-villa.jpg" alt="Kampala residence interior" width={1200} height={1600} className="aspect-[3/4] w-full rounded-md object-cover md:col-span-2" /><Image src="/prototype/process-1.jpg" alt="Craftsmanship detail" width={800} height={1067} className="mt-12 aspect-[3/4] w-full rounded-md object-cover" /></div></section>
  <section className="bg-obsidian px-6 py-32 text-canvas lg:px-12"><div className="mx-auto max-w-5xl"><h2 className="mb-16 font-serif text-4xl leading-tight text-balance md:text-6xl">We treat each project as a private commission — discreet, considered, slow.</h2><div className="grid grid-cols-1 gap-12 border-t border-canvas/10 pt-16 md:grid-cols-3">{[['Provenance','Every piece arrives with documentation from its maison of origin.'],['Discretion','Client relationships are confidential, end to end.'],['Permanence','We curate for inheritance, not for trend cycles.']].map(([title,body]) => <div key={title}><h4 className="mb-3 font-serif text-2xl">{title}</h4><p className="leading-relaxed text-canvas/60">{body}</p></div>)}</div></div></section>
  <section className="px-6 py-24 lg:px-12"><div className="mx-auto max-w-7xl"><div className="mb-12"><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">The Album</p><h2 className="font-serif text-4xl leading-tight md:text-5xl">From the studio.</h2><p className="mt-4 max-w-sm text-sm leading-relaxed text-muted-foreground">Moments, projects and pieces we have lived with — an evolving record of the work.</p></div><div className="grid grid-cols-1 gap-x-8 gap-y-14 sm:grid-cols-2 lg:grid-cols-3">{[['Villa in Kampala','/prototype/hero-villa.jpg','A considered residence shaped around light and material.'],['Material study','/prototype/process-1.jpg','The details that make a room feel lived in.'],['An object with presence','/prototype/feature-console.jpg','Sourced for rooms meant to be lived in.']].map(([title,image,body]) => <article key={title}><div className="mb-5 overflow-hidden rounded-md bg-muted"><Image src={image} alt={title} width={800} height={1000} className="aspect-[4/5] w-full object-cover transition-transform duration-700 hover:scale-[1.02]" /></div><h3 className="font-serif text-2xl font-medium leading-tight">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p></article>)}</div></div></section>
</main><SiteFooter /></> }
