import type { Metadata } from 'next'
import { SiteFooter } from '@/components/site-footer'
import { SiteHeader } from '@/components/site-header'
import PageLoadError from '@/components/system/page-load-error'
import { db } from '@/lib/db/client'
import { products as productsTable } from '@/lib/db/schema'
import { desc, eq } from 'drizzle-orm'
import { safeQuery } from '@/lib/server/safe-query'
import CategoryDirectory from '@/components/collections/category-directory'
import { SchemaScript } from '@/components/seo/schema-script'
import Link from 'next/link'
import Image from 'next/image'
import { ArrowRight } from '@/components/ui/luxury-icons'

export const dynamic = 'force-dynamic'
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL?.trim() || 'https://therevampug.com').replace(/\/$/, '')
export const metadata: Metadata = { title: 'Furniture, Chairs and Sofas in Uganda', description: 'Explore The Revamp UG collection of chairs, sofas, tables, lighting, décor, and considered furniture for residential and commercial spaces.', keywords: ['chairs Uganda', 'sofas Uganda', 'furniture Kampala', 'interior décor Uganda', 'The Revamp UG collection'], alternates: { canonical: `${SITE_URL}/collections` }, openGraph: { type: 'website', url: `${SITE_URL}/collections`, title: 'Furniture, Chairs and Sofas | The Revamp UG', description: 'Considered furniture, lighting, and interior objects sourced by The Revamp UG.' }, twitter: { card: 'summary_large_image', title: 'Furniture, Chairs and Sofas | The Revamp UG', description: 'Considered furniture, lighting, and interior objects sourced by The Revamp UG.' } }

async function getPublishedProducts() { return db.query.products.findMany({ where: eq(productsTable.status, 'published'), orderBy: [desc(productsTable.featured), desc(productsTable.createdAt)], with: { productImages: true, productVariants: true, subCategory: { with: { category: true } } }, limit: 100 }) }
function slug(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') }

export default async function CollectionsPage() {
  const result = await safeQuery(getPublishedProducts(), 'published collections', [])
  const products = result.data
  const categories = Array.from(products.reduce((map, product) => { const category = product.subCategory?.category; const subCategory = product.subCategory; const name = category?.name || subCategory?.name; if (!name) return map; const categorySlug = slug(name); const image = product.productImages?.find((entry) => entry.isPrimary)?.url || product.productImages?.[0]?.url || null; const current = map.get(categorySlug); const subSlug = subCategory?.slug || (subCategory?.name ? slug(subCategory.name) : undefined); const subcategories = current?.subcategories || []; const existing = subSlug ? subcategories.find((item) => item.slug === subSlug) : undefined; if (subSlug && existing) existing.productCount += 1; else if (subSlug) subcategories.push({ name: subCategory?.name || 'Collection', slug: subSlug, productCount: 1, image }); map.set(categorySlug, { name, slug: categorySlug, productCount: (current?.productCount || 0) + 1, image: current?.image || image, subcategories }); return map }, new Map<string, { name: string; slug: string; productCount: number; image: string | null; subcategories: Array<{ name: string; slug: string; productCount: number; image: string | null }> }>()).values())
  const productItems = products.map((product, index) => ({ '@type': 'ListItem', position: index + 1, name: product.name, url: `${SITE_URL}/collections/${product.subCategory?.category?.name ? `${slug(product.subCategory.category.name)}/` : ''}${encodeURIComponent(product.slug)}` }))

  return <><SchemaScript schema={{ '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'The Revamp UG Collection', url: `${SITE_URL}/collections`, mainEntity: { '@type': 'ItemList', itemListElement: productItems } }} /><SiteHeader /><main className="min-h-screen bg-canvas text-obsidian"><section className="relative overflow-hidden bg-obsidian text-ivory"><div className="absolute inset-0"><Image src="/prototype/hero-natural-light.jpg" alt="Objects for refined living" fill priority className="object-cover opacity-70" /><div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/30 to-black/10" /></div><div className="relative mx-auto flex min-h-[34rem] max-w-[1440px] items-end px-5 pb-10 pt-28 sm:min-h-[40rem] sm:px-8 sm:pb-14 lg:px-12"><div className="max-w-xl"><p className="text-[10px] uppercase tracking-[0.28em] text-ivory/65">The collection</p><h1 className="mt-5 font-serif text-6xl font-light leading-[0.84] sm:text-8xl">Objects for<br />refined living.</h1><p className="mt-6 max-w-sm text-sm leading-6 text-ivory/75">A curated collection of furniture, lighting, décor, and distinctive objects from around the world.</p><Link href="#categories" className="mt-8 inline-flex items-center gap-3 border border-ivory/50 px-4 py-3 text-[10px] uppercase tracking-[0.18em]">Explore collections <ArrowRight className="size-3" /></Link></div></div></section><div id="categories" className="mx-auto max-w-[1440px]">{result.error ? <div className="mx-5 my-12 flex min-h-64 items-center justify-center border border-border bg-canvas p-6 sm:mx-8 lg:mx-12"><PageLoadError title="The collection is taking longer than expected." message="We could not load the current edit. Your cart and saved pieces were not changed." /></div> : products.length === 0 ? <div className="mx-5 my-12 border border-dashed border-border p-12 text-center sm:mx-8 lg:mx-12"><p className="font-serif text-3xl">The next edit is on its way.</p><p className="mt-3 text-sm text-muted-foreground">No published pieces are available just yet. Return soon or speak with our studio.</p></div> : <CategoryDirectory categories={categories} />}</div></main><SiteFooter /></>
}
