'use client'

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts'

const revenueData = [
  { month: 'Jan', revenue: 0 },
    { month: 'Feb', revenue: 0 },
      { month: 'Mar', revenue: 0 },
        { month: 'Apr', revenue: 0 },
          { month: 'May', revenue: 0 },
            { month: 'Jun', revenue: 0 },
            ]

            const ordersData = [
              { week: 'Week 1', orders: 0 },
                { week: 'Week 2', orders: 0 },
                  { week: 'Week 3', orders: 0 },
                    { week: 'Week 4', orders: 0 },
                    ]

                    export default function AdminDashboard() {
                      return (
                          <div className="space-y-8 p-8">
                                <div>
                                        <h1 className="font-serif text-4xl font-light text-foreground">Dashboard</h1>
                                                <p className="text-muted-foreground mt-2">Welcome back. Here's your business overview.</p>
                                                      </div>

                                                            {/* KPI Cards */}
                                                                  <div className="grid gap-6 md:grid-cols-4">
                                                                          <Card>
                                                                                    <CardHeader className="pb-3">
                                                                                                <CardTitle className="text-sm font-medium text-muted-foreground">Total Revenue</CardTitle>
                                                                                                          </CardHeader>
                                                                                                                    <CardContent>
                                                                                                                                <div className="text-3xl font-light text-foreground">UGX 131M</div>
                                                                                                                                            <p className="text-xs text-muted-foreground mt-2">+12% from last month</p>
                                                                                                                                                      </CardContent>
                                                                                                                                                              </Card>

                                                                                                                                                                      <Card>
                                                                                                                                                                                <CardHeader className="pb-3">
                                                                                                                                                                                            <CardTitle className="text-sm font-medium text-muted-foreground">Total Orders</CardTitle>
                                                                                                                                                                                                      </CardHeader>
                                                                                                                                                                                                                <CardContent>
                                                                                                                                                                                                                            <div className="text-3xl font-light text-foreground">847</div>
                                                                                                                                                                                                                                        <p className="text-xs text-muted-foreground mt-2">+8% from last month</p>
                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                          </Card>

                                                                                                                                                                                                                                                                  <Card>
                                                                                                                                                                                                                                                                            <CardHeader className="pb-3">
                                                                                                                                                                                                                                                                                        <CardTitle className="text-sm font-medium text-muted-foreground">Active Clients</CardTitle>
                                                                                                                                                                                                                                                                                                  </CardHeader>
                                                                                                                                                                                                                                                                                                            <CardContent>
                                                                                                                                                                                                                                                                                                                        <div className="text-3xl font-light text-foreground">342</div>
                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-muted-foreground mt-2">+15% from last month</p>
                                                                                                                                                                                                                                                                                                                                              </CardContent>
                                                                                                                                                                                                                                                                                                                                                      </Card>

                                                                                                                                                                                                                                                                                                                                                              <Card>
                                                                                                                                                                                                                                                                                                                                                                        <CardHeader className="pb-3">
                                                                                                                                                                                                                                                                                                                                                                                    <CardTitle className="text-sm font-medium text-muted-foreground">Pending Projects</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                              </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                        <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-3xl font-light text-foreground">24</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-xs text-muted-foreground mt-2">5 high priority</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Charts */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid gap-6 md:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardTitle>Revenue Trend</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <CardDescription>Monthly revenue over the past 6 months</CardDescription>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ResponsiveContainer width="100%" height={300}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <LineChart data={revenueData}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <CartesianGrid strokeDasharray="3 3" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <XAxis dataKey="month" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <YAxis />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Tooltip />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Line type="monotone" dataKey="revenue" stroke="#b88a3f" strokeWidth={2} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </LineChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <CardTitle>Orders by Week</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardDescription>Order volume this month</CardDescription>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ResponsiveContainer width="100%" height={300}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <BarChart data={ordersData}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <CartesianGrid strokeDasharray="3 3" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <XAxis dataKey="week" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <YAxis />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Tooltip />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Bar dataKey="orders" fill="#b88a3f" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </BarChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Recent Activity */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <CardTitle>Recent Activity</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CardDescription>Latest updates from your business</CardDescription>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { action: 'New order placed', user: 'Client #2847', time: '2 hours ago' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { action: 'Project completed', user: 'The Nakasero Residence', time: '4 hours ago' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { action: 'New consultation booked', user: 'John Doe', time: '6 hours ago' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { action: 'Payment received', user: 'Order #5634', time: '8 hours ago' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ].map((activity, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={idx} className="flex items-start justify-between border-b border-border/20 pb-3 last:border-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="font-medium text-foreground">{activity.action}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-muted-foreground">{activity.user}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs text-muted-foreground">{activity.time}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              