import Image from 'next/image'
import Link from 'next/link'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'

export const metadata = { title: 'Architecture — The Revamp UG', description: 'Bespoke residential architecture in Uganda. From hand-drawn concept sketches and 3D renders to construction documentation — we design homes born from a unified vision.' }

const phases = [
  ['01', 'Concept & Sketch', 'We begin in pencil — sketching massing, light and circulation against the site. Every project starts as an idea drawn by hand before it becomes a building.'],
  ['02', '3D Visualisation', 'Photoreal renders let you walk the house before a single block is laid — testing materials, daylight and the spatial drama at full scale.'],
  ['03', 'Floor Plans & Documentation', 'Fully dimensioned drawings, structural coordination and permit-ready packages — the technical backbone of a beautiful build.'],
  ['04', 'Build Supervision', 'We remain on site, in dialogue with contractors, to protect the integrity of the design from foundation to final styling.'],
]

export default function ArchitecturePage() {
  return <><SiteHeader /><main>
    <section className="relative"><div className="relative h-[78vh] min-h-[520px] w-full overflow-hidden"><Image src="/prototype/arch-render-villa.jpg" alt="Photoreal 3D render of a modernist luxury villa at golden hour" fill className="object-cover" priority /><div className="absolute inset-0 bg-gradient-to-t from-obsidian/80 via-obsidian/20 to-transparent" /><div className="absolute inset-0 flex items-end"><div className="mx-auto w-full max-w-7xl px-6 pb-16 lg:px-12"><div className="mb-6 inline-flex items-center gap-3"><span className="h-px w-8 bg-gilded" /><span className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">The Architectural Practice</span></div><h1 className="max-w-5xl font-serif text-5xl font-medium leading-[1.02] text-canvas text-balance md:text-7xl lg:text-8xl">Houses drawn <span className="italic">by hand</span>,<br className="hidden md:block" /> built to last <span className="italic">generations</span>.</h1></div></div></div></section>
    <section className="px-6 py-24 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-16 lg:grid-cols-12"><div className="lg:col-span-5"><p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">From sketch to keys</p><h2 className="mt-6 font-serif text-4xl font-medium leading-tight md:text-5xl">An atelier that designs the <span className="italic">vessel</span> as well as its contents.</h2></div><div className="space-y-6 text-lg leading-relaxed text-muted-foreground lg:col-span-7 lg:pt-4"><p>Most of our clients arrive asking for furniture. Many discover the rooms themselves want reimagining — the proportions, the openings, the play of shadow across a hallway in the late afternoon.</p><p>The Revamp UG operates a full architectural practice alongside its sourcing concierge. From the first pencil sketch to the final keys, our studio shapes private residences across Kampala and the wider region — with the same reverence for material and craft we bring to a Boca do Lobo cabinet.</p></div></div></section>
    <section className="px-6 pb-24 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-12 gap-4 md:gap-6"><figure className="col-span-12 md:col-span-8"><div className="overflow-hidden rounded-md bg-muted"><Image src="/prototype/arch-interior-3d.jpg" alt="3D interior render of a double-height living room with travertine walls and sculptural staircase" width={1000} height={1200} className="aspect-[4/5] w-full object-cover md:aspect-[5/6]" /></div><figcaption className="mt-3 text-[10px] uppercase tracking-[0.25em] text-muted-foreground">3D Render · Private Residence, Naguru</figcaption></figure><div className="col-span-12 flex flex-col gap-4 md:col-span-4 md:gap-6"><figure><Image src="/prototype/arch-plan.jpg" alt="Architectural floor plan in fine charcoal and gold linework" width={700} height={700} className="aspect-square w-full rounded-md object-cover" /><figcaption className="mt-3 text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Floor Plan · Ground Level</figcaption></figure><figure><Image src="/prototype/arch-sketch.jpg" alt="Hand-drawn architectural concept sketch in pencil and sepia wash" width={700} height={700} className="aspect-square w-full rounded-md object-cover" /><figcaption className="mt-3 text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Concept Sketch · Courtyard Study</figcaption></figure></div></div></section>
    <section className="bg-obsidian px-6 py-32 text-canvas lg:px-12"><div className="mx-auto max-w-7xl"><div className="mb-20 max-w-3xl"><span className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">The Practice</span><h2 className="mt-6 font-serif text-4xl leading-[1.05] text-balance md:text-6xl">Four phases, one continuous <span className="italic">conversation</span>.</h2></div><div className="grid grid-cols-1 gap-x-16 gap-y-16 md:grid-cols-2">{phases.map(([number,title,body]) => <div key={number} className="border-t border-canvas/15 pt-8"><div className="mb-4 flex items-baseline gap-6"><span className="font-serif text-2xl text-gilded">{number}</span><h3 className="font-serif text-3xl font-medium">{title}</h3></div><p className="max-w-[44ch] leading-relaxed text-canvas/60">{body}</p></div>)}</div></div></section>
    <section className="px-6 py-24 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-12 md:grid-cols-3">{[['New Residences','Ground-up family homes, retreats and pied-à-terres designed in dialogue with the Ugandan landscape.'],['Renovations','Reimagining existing structures — opening volumes, restoring proportion, modernising services.'],['Interior Architecture','Joinery, stairs, ceilings and built-ins designed as architecture, not decoration.']].map(([title,body]) => <div key={title} className="space-y-3"><h4 className="font-serif text-2xl font-medium">{title}</h4><p className="leading-relaxed text-muted-foreground">{body}</p></div>)}</div></section>
    <section className="px-6 pb-32 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-10 rounded-md bg-obsidian p-12 text-canvas md:flex-row md:items-end md:p-20"><div><h3 className="mb-4 font-serif text-4xl leading-tight md:text-5xl">Have a site, a plot, or a feeling?</h3><p className="max-w-md text-canvas/60">Bring us your plans — or just your aspirations. We will sketch the first moves with you.</p></div><Link href="/contact" className="rounded-full bg-canvas px-10 py-4 text-[11px] font-semibold uppercase tracking-[0.2em] text-obsidian transition-colors hover:bg-gilded">Start a Design Conversation</Link></div></section>
  </main><SiteFooter /></>
}
