import Image from 'next/image'
import Link from 'next/link'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { getPublishedProjects } from '@/lib/db/queries'
import { resolveProductImageUrls } from '@/lib/utils'

export const dynamic = 'force-dynamic'
export const metadata = { title: 'Architecture - The Revamp UG', description: 'Bespoke residential architecture and interior architecture in Uganda, shaped from the first sketch to the final installation.' }

const phases = [
  ['01', 'Concept & Sketch', 'We begin with the site, the light and the way you want to live. The first move is a conversation, translated into proportion, circulation and material intent.'],
  ['02', '3D Visualisation', 'Photoreal renders let you walk the house before a single block is laid - testing materials, daylight and spatial drama at full scale.'],
  ['03', 'Documentation', 'Fully coordinated drawings, specifications and permit-ready packages form the technical backbone of a beautiful, buildable project.'],
  ['04', 'Build Supervision', 'We remain involved through procurement and installation, protecting the design from the first foundation to the final object.'],
]

export default async function ArchitecturePage() {
  const projects = await getPublishedProjects(100, 0)
  const heroProject = projects[0]
  const heroImage = heroProject ? resolveProductImageUrls(heroProject)[0] : '/prototype/arch-render-villa.jpg'
  const architectureProjects = projects.slice(0, 6)
  return <><SiteHeader /><main>
    <section className="relative"><div className="relative h-[78vh] min-h-[520px] w-full overflow-hidden"><Image src={heroImage} alt={heroProject ? `${heroProject.title}${heroProject.location ? ` in ${heroProject.location}` : ''}` : 'Modernist luxury residence at golden hour'} fill className="object-cover" priority sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-t from-obsidian/80 via-obsidian/20 to-transparent" /><div className="absolute inset-0 flex items-end"><div className="mx-auto w-full max-w-7xl px-6 pb-16 lg:px-12"><div className="mb-6 inline-flex items-center gap-3"><span className="h-px w-8 bg-gilded" /><span className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">The Architectural Practice</span></div><h1 className="max-w-5xl font-serif text-5xl font-medium leading-[1.02] text-canvas text-balance md:text-7xl lg:text-8xl">Houses drawn <span className="italic">by hand</span>,<br className="hidden md:block" /> built to last <span className="italic">generations</span>.</h1>{heroProject && <p className="mt-6 text-[10px] uppercase tracking-[0.25em] text-canvas/65">Featured project · {heroProject.title}{heroProject.location ? ` · ${heroProject.location}` : ''}</p>}</div></div></div></section>
    <section className="px-6 py-24 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-16 lg:grid-cols-12"><div className="lg:col-span-5"><p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">From sketch to keys</p><h2 className="mt-6 font-serif text-4xl font-medium leading-tight md:text-5xl">An atelier that designs the <span className="italic">vessel</span> as well as its contents.</h2></div><div className="space-y-6 text-lg leading-relaxed text-muted-foreground lg:col-span-7 lg:pt-4"><p>Our live portfolio is a record of how the practice works: spaces shaped around light, proportion, material and the lives that happen inside them.</p><p>The Revamp UG operates an architectural and interior practice alongside its sourcing concierge. From the first pencil sketch to the final keys, we shape residences and considered commercial spaces across Kampala and the wider region - bringing furniture, finishes and architecture into one conversation.</p><Link href="/portfolio" className="inline-flex text-[10px] font-semibold uppercase tracking-[0.2em] text-gilded hover:text-obsidian">View the full project archive →</Link></div></div></section>
    {architectureProjects.length > 0 && <section className="px-6 pb-24 lg:px-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 border-b border-border pb-8 md:flex-row md:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">Built work & live studies</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">The work behind the practice.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground md:text-right">{projects.length} published {projects.length === 1 ? 'project' : 'projects'} from the live Revamp archive.</p></div><div className="mt-12 grid gap-x-6 gap-y-14 md:grid-cols-2 lg:grid-cols-3">{architectureProjects.map((project, index) => { const image = resolveProductImageUrls(project)[0]; return <Link key={project.id} href={`/portfolio/${project.slug}`} className={`group ${index === 0 ? 'md:col-span-2 lg:col-span-2' : ''}`}><div className={`relative overflow-hidden rounded-md bg-muted ${index === 0 ? 'aspect-[16/9]' : 'aspect-[4/3]'}`}><Image src={image} alt={project.title} fill sizes={index === 0 ? '(max-width: 768px) 100vw, 66vw' : '(max-width: 768px) 100vw, 33vw'} className="object-cover transition duration-700 group-hover:scale-[1.03]" /></div><div className="mt-4 flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.2em] text-gilded">{project.category || 'Project'}{project.location ? ` · ${project.location}` : ''}</p><h3 className="mt-2 font-serif text-2xl leading-tight">{project.title}</h3><p className="mt-2 line-clamp-2 max-w-lg text-sm leading-6 text-muted-foreground">{project.shortDescription || project.description || project.longDescription || 'A considered Revamp project shaped around material, light and everyday life.'}</p></div><span className="mt-1 text-lg text-muted-foreground transition-colors group-hover:text-gilded">↗</span></div></Link> })}</div></div></section>}
    <section className="px-6 pb-24 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-12 gap-4 md:gap-6"><figure className="col-span-12 md:col-span-8"><div className="overflow-hidden rounded-md bg-muted"><Image src="/prototype/arch-interior-3d.jpg" alt="3D interior render of a double-height living room with travertine walls and sculptural staircase" width={1000} height={1200} className="aspect-[4/5] w-full object-cover md:aspect-[5/6]" /></div><figcaption className="mt-3 text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Design study · Interior architecture</figcaption></figure><div className="col-span-12 flex flex-col gap-4 md:col-span-4 md:gap-6"><figure><Image src="/prototype/arch-plan.jpg" alt="Architectural floor plan in fine charcoal and gold linework" width={700} height={700} className="aspect-square w-full rounded-md object-cover" /><figcaption className="mt-3 text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Documentation · Ground level</figcaption></figure><figure><Image src="/prototype/arch-sketch.jpg" alt="Hand-drawn architectural concept sketch in pencil and sepia wash" width={700} height={700} className="aspect-square w-full rounded-md object-cover" /><figcaption className="mt-3 text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Concept · Courtyard study</figcaption></figure></div></div></section>
    <section className="bg-obsidian px-6 py-32 text-canvas lg:px-12"><div className="mx-auto max-w-7xl"><div className="mb-20 max-w-3xl"><span className="text-[10px] font-semibold uppercase tracking-[0.3em] text-gilded">The Practice</span><h2 className="mt-6 font-serif text-4xl leading-[1.05] text-balance md:text-6xl">Four phases, one continuous <span className="italic">conversation</span>.</h2></div><div className="grid grid-cols-1 gap-x-16 gap-y-16 md:grid-cols-2">{phases.map(([number, title, body]) => <div key={number} className="border-t border-canvas/15 pt-8"><div className="mb-4 flex items-baseline gap-6"><span className="font-serif text-2xl text-gilded">{number}</span><h3 className="font-serif text-3xl font-medium">{title}</h3></div><p className="max-w-[44ch] leading-relaxed text-canvas/60">{body}</p></div>)}</div></div></section>
    <section className="px-6 py-24 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-12 md:grid-cols-3">{[['New Residences', 'Ground-up family homes, retreats and pied-à-terres designed in dialogue with the Ugandan landscape.'], ['Renovations', 'Reimagining existing structures - opening volumes, restoring proportion, modernising services.'], ['Interior Architecture', 'Joinery, stairs, ceilings and built-ins designed as architecture, not decoration.']].map(([title, body]) => <div key={title} className="space-y-3"><h4 className="font-serif text-2xl font-medium">{title}</h4><p className="leading-relaxed text-muted-foreground">{body}</p></div>)}</div></section>
    <section className="px-6 pb-32 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-10 rounded-md bg-obsidian p-12 text-canvas md:flex-row md:items-end md:p-20"><div><h3 className="mb-4 font-serif text-4xl leading-tight md:text-5xl">Have a site, a plot, or a feeling?</h3><p className="max-w-md text-canvas/60">Bring us your plans - or just your aspirations. We will sketch the first moves with you.</p></div><Link href="/contact?interest=service_inquiry&service=Architecture" className="rounded-full bg-canvas px-10 py-4 text-[11px] font-semibold uppercase tracking-[0.2em] text-obsidian transition-colors hover:bg-gilded">Start a Design Conversation</Link></div></section>
  </main><SiteFooter /></>
}
